### ISSUE TITLE
Decide on the type of sidebar

### ISSUE THREAD

**Issue by 5pitty1** [5pitty1/Zeta-Omicron#1]
I need help choosing what sidebar I should use.

![version 1](https://cloud.githubusercontent.com/assets/7350286/5905498/58663cde-a545-11e4-98c6-394f947dfb01.jpg)
![version 2](https://cloud.githubusercontent.com/assets/7350286/5905499/5866d32e-a545-11e4-8f58-949fa3bd22d4.jpg)

**Comment by Nesantsi** [comment]
Top side bar

**Comment by Nesantsi** [comment]
Aka the first one

**Comment by 5pitty1** [comment]
Decided to make a nicer version of the first one
![image](https://cloud.githubusercontent.com/assets/7350286/6011336/8bf44d2a-aaef-11e4-82ab-dbe14008ccd4.png)
